### ISSUE TITLE
RSA not working on all platforms

### ISSUE THREAD

**Issue by voidrealms** [PointyCastle/pointycastle#117]
making a set of tutorials, the following code works on mac but not linux.

https://pastebin.com/wZGsjWWF

On Linux it errors out with:
Unhandled exception:
Invalid argument(s): Input too large for RSA cipher
#0      RSAEngine._convertInput (package:pointycastle/asymmetric/rsa.dart:83:8)
#1      RSAEngine.processBlock (package:pointycastle/asymmetric/rsa.dart:73:17)
#2      BaseAsymmetricBlockCipher.process (package:pointycastle/src/impl/base_asymmetric_block_cipher.dart:16:15)
#3      main (file:///home/rootshell/Code/encryption6/bin/main.dart:37:32)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

Process finished with exit code 255

import 'package:pointycastle/pointycastle.dart';
import 'dart:convert';
import 'dart:typed_data';
import 'dart:math';
import 'package:collection/collection.dart';
import "package:bignum/bignum.dart";

//https://pub.dartlang.org/packages/pointycastle
//dependencies:
//pointycastle: "^0.11.1"

main(List<String> arguments) {

  var modulus = new BigInteger("20620915813302906913761247666337410938401372343750709187749515126790853245302593205328533062154315527282056175455193812046134139935830222032257750866653461677566720508752544506266533943725970345491747964654489405936145559121373664620352701801574863309087932865304205561439525871868738640172656811470047745445089832193075388387376667722031640892525639171016297098395245887609359882693921643396724693523583076582208970794545581164952427577506035951122669158313095779596666008591745562008787129160302313244329988240795948461701615228062848622019620094307696506764461083870202605984497833670577046553861732258592935325691");
  var publicExponent = new BigInteger("65537");
  var privateExponent = new BigInteger("11998058528661160053642124235359844880039079149364512302169225182946866898849176558365314596732660324493329967536772364327680348872134489319530228055102152992797567579226269544119435926913937183793755182388650533700918602627770886358900914370472445911502526145837923104029967812779021649252540542517598618021899291933220000807916271555680217608559770825469218984818060775562259820009637370696396889812317991880425127772801187664191059506258517954313903362361211485802288635947903604738301101038823790599295749578655834195416886345569976295245464597506584866355976650830539380175531900288933412328525689718517239330305");
  var p = new BigInteger("144173682842817587002196172066264549138375068078359231382946906898412792452632726597279520229873489736777248181678202636100459215718497240474064366927544074501134727745837254834206456400508719134610847814227274992298238973375146473350157304285346424982280927848339601514720098577525635486320547905945936448443");
  var q = new BigInteger("143028293421514654659358549214971921584534096938352096320458818956414890934365483375293202045679474764569937266017713262196941957149321696805368542065644090886347646782188634885321277533175667840285448510687854061424867903968633218073060468434469761149335255007464091258725753837522484082998329871306803923137");
  // dP = 68805717049526308324575273108573116001662526577152473869179706227957595091947965115631041308417430436199124027318143092441125820376694663934988040410650411495368889020042904305193636218299757516719158446153874604179501966374024692112438317379995729651506791282977824993147390378095874103264534184571632120755
  // dQ = 50784570363590735217102910420562378736776300956031757348933834583758403833600634727605365085416808486374756857656471727593921591511126781583852266259785128933660523683133642580243620064955640182544858428730432641246268155779942551300183363603309753909166293605500547836955434209670082619152099365325073276033
  // Qinv = 55230685559710427662641419127391743688498562899704993951405017803347590263833235040975158906547337992492501961820323076137293399600978620698955537627140829092176376250413837145798422716237647195575076578845234764700372691872271724982949541941613766324969755382993478116416238708238612702107474463263158193372

  var pubk = new RSAPublicKey(modulus, publicExponent);
  var privk = new RSAPrivateKey(modulus, privateExponent, p, q);

  PublicKeyParameter<RSAPublicKey> pubpar = new PublicKeyParameter<RSAPublicKey>(pubk);
  PrivateKeyParameter<RSAPrivateKey> privpar = new PrivateKeyParameter<RSAPrivateKey>(privk);

  AsymmetricBlockCipher cipher = new AsymmetricBlockCipher("RSA");

  //Encrypt with the public key
  cipher.reset();
  cipher.init(true, pubpar);
  Uint8List plain_text = createUint8ListFromString('Hello World');
  Uint8List encrypted = cipher.process(plain_text);

  //Decrypt with the private key
  cipher.reset();
  cipher.init(false, privpar);
  Uint8List decrypted = cipher.process(encrypted);

  print(UTF8.decode(decrypted));

}

//From tutorial 2
Uint8List createUint8ListFromString(String value) => new Uint8List.fromList(UTF8.encode(value));

//From tutorial 2
void displayUint8List(String title, Uint8List value) {
  print(title);
  print(value);
  print(BASE64.encode(value));
  print('');
}

**Comment by voidrealms** [comment]
Additional info:
  print('OB = ${cipher.outputBlockSize}');
  print('IB = ${cipher.inputBlockSize}');

OB = 0
IB = -1

modified rsa.dart line 83:
    if (inpLen > (inputBlockSize + 1)) {
      print('inpLen= ${inpLen} inputBlockSize=${inputBlockSize}');
       throw new ArgumentError("Input too large for RSA cipher");
    }


inpLen= 11 inputBlockSize=-1

**Comment by stevenroose** [comment]
I noticed some issues as well. I will investigate this [once we migrated to BigInt](https://github.com/PointyCastle/pointycastle/pull/122). Once that migration is done, I'll also ping you to test again, because I suspect that BigInt support might solve some problems.
